services:
  - type: web
    name: finance-frontend
    plan: free
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"