services:
  - type: web
    name: finance-backend
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: finance-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: finance-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: finance-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: finance-db
          property: database
      - key: DB_PORT
        value: "5432"

databases:
  - name: finance-db
    plan: free
    databaseName: accountant
    user: accountant_user